In [1]:
import numpy as np
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit import Aer, execute
import matplotlib.pyplot as plt
import time
from scipy.optimize import minimize, approx_fprime
import csv
from itertools import chain

import sys
sys.path.append("..")

import Entangler
import TensorNetwork
import hamiltonians
import TNOptimize
import uuid
import json
import utils
plt.rcParams.update({'font.size': 14})

/home/alexey/quantumenv/lib/python3.6/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning


In [2]:
n_qubits = 10
depth = 4

q, c = QuantumRegister(n_qubits), ClassicalRegister(n_qubits)
ent = Entangler.IsingEntangler()
TN = TensorNetwork.Checkerboard(q, c, ent, depth=depth)

tol = 1e-6
method = "L-BFGS-B"



In [3]:
10 % 3


1

In [4]:
%%time


J = 1

# np.random.seed(0)

h_vals = np.linspace(0, 2, num=1001)

h_iter = chain(h_vals, reversed(h_vals))

x_0 = np.random.rand(TN.n_params)

datetime = time.strftime("%Y-%m-%d_%H-%M-%S")

h_base = hamiltonians.xxz_heisenberg_model(n_qubits, 1, 0)
H_base = hamiltonians.explicit_hamiltonian(h_base)

h_field = hamiltonians.xxz_heisenberg_model(n_qubits, 0, 1)
H_field = hamiltonians.explicit_hamiltonian(h_field)

with open("vqe_" + datetime + ".csv", "a", newline='') as fd:
    statewriter = csv.writer(fd, delimiter=',', quoting=csv.QUOTE_MINIMAL)
    for i, h in enumerate(h_iter):
        if np.isclose(h, 1):
            continue
        H = H_base + h * H_field
        f = TNOptimize.build_objective_function(TN, explicit_H=H)
        res = minimize(f, x_0, options={'maxiter': 300}, callback=None, 
               tol=tol, method=method)
        circ = TN.construct_circuit(res.x)
        state = utils.get_state(circ)
        if (i % 10 == 0):
            print(i)
            print(res.fun)
            print(res.nit)
            print(res.message)
        if (h>1):
            state_label = 1
        else:
            state_label = 0
        total_data = np.concatenate((state, res.x, [h, res.fun, state_label]))
        statewriter.writerow(total_data)
        x_0 = res.x
#     for h in reversed(h_vals):
#         if np.isclose(h, 1):
#             continue
#         ham_dict = hamiltonians.ising_model(n_qubits, J, h)
#         H = hamiltonians.explicit_hamiltonian(ham_dict)
#         f = TNOptimize.build_objective_function(TN, explicit_H=H)
#         res = minimize(f, x_0, options={'maxiter': 300}, callback=None, 
#                tol=tol, method=method)
#         circ = TN.construct_circuit(res.x)
#         state = utils.get_state(circ)
#         print(res.fun)
#         print(res.nit)
#         print(res.message)        
#         if (h>1):
#             state_label = 1
#         else:
#             state_label = 0
#         total_data = np.concatenate((state, res.x, [h, res.fun, state_label]))
#         statewriter.writerow(total_data)
#         x_0 = res.x


/home/alexey/quantumenv/lib/python3.6/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
/home/alexey/quantumenv/lib/python3.6/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
/home/alexey/quantumenv/lib/python3.6/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
/home/alexey/quantumenv/lib/python3.6/site-packages/marshm

0
-12.437152892899405
142
b'STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT'
10
-12.512418905039567
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
20
-12.588078052311907
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
30
-12.671756196708879
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
40
-12.748944923506421
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
50
-12.826651144313956
7
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
60
-12.904725870191438
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
70
-12.983458483320259
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
80
-13.06282821329157
14
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
90
-13.142444039155569
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
100
-13.222573373923044
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
110
-13.303025420924214
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
120
-13.389107616625697
1
b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
130

In [ ]:
h_vals = np.linspace(0, 2, num=101)

In [ ]:
%%time
approx_fprime(x0, f, eps)

In [ ]:
a = reversed(h_vals)

In [ ]:
next(a)

In [6]:
res.x

array([ 1.57079601e+00,  7.85397845e+00, -1.57079418e+00,  1.11707686e+00,
       -1.57079637e+00,  4.71238895e+00,  4.71238904e+00, -1.85435088e-08,
        2.53792274e+00,  1.57079633e+00])

In [7]:
total_data

array([-7.89362044e-07+5.26207430e-07j,  2.19155347e-01+4.49411691e-01j,
        2.83833416e-01+4.11629305e-01j,  8.71601477e-07-4.32499853e-07j,
        7.89361991e-07-5.26207415e-07j, -2.19155343e-01-4.49411663e-01j,
       -2.83833392e-01-4.11629288e-01j, -8.71601438e-07+4.32499812e-07j,
        1.57079601e+00+0.00000000e+00j,  7.85397845e+00+0.00000000e+00j,
       -1.57079418e+00+0.00000000e+00j,  1.11707686e+00+0.00000000e+00j,
       -1.57079637e+00+0.00000000e+00j,  4.71238895e+00+0.00000000e+00j,
        4.71238904e+00+0.00000000e+00j, -1.85435088e-08+0.00000000e+00j,
        2.53792274e+00+0.00000000e+00j,  1.57079633e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j, -1.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j])

In [8]:
state

array([-7.89362044e-07+5.26207430e-07j,  2.19155347e-01+4.49411691e-01j,
        2.83833416e-01+4.11629305e-01j,  8.71601477e-07-4.32499853e-07j,
        7.89361991e-07-5.26207415e-07j, -2.19155343e-01-4.49411663e-01j,
       -2.83833392e-01-4.11629288e-01j, -8.71601438e-07+4.32499812e-07j])

In [9]:
res.x

array([ 1.57079601e+00,  7.85397845e+00, -1.57079418e+00,  1.11707686e+00,
       -1.57079637e+00,  4.71238895e+00,  4.71238904e+00, -1.85435088e-08,
        2.53792274e+00,  1.57079633e+00])

In [10]:
TN.n_params

10

In [11]:
len(state)

8